# Generated by Django 4.2.29 on 2026-03-18 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('level_number', models.IntegerField(unique=True)),
                ('min_avg_score', models.FloatField(default=0)),
                ('min_submissions', models.IntegerField(default=0)),
                ('reward_multiplier', models.FloatField(default=1.0)),
                ('description', models.TextField(blank=True)),
                ('badge_color', models.CharField(default='#6b7280', max_length=20)),
                ('icon', models.CharField(default='⬡', max_length=10)),
            ],
            options={
                'ordering': ['level_number'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('worker', 'Worker'), ('company', 'Company')], default='worker', max_length=10)),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('avg_score', models.FloatField(default=0)),
                ('total_submissions', models.IntegerField(default=0)),
                ('bio', models.TextField(blank=True)),
                ('company_name', models.CharField(blank=True, max_length=100)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core.level')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('reward', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deadline', models.DateTimeField()),
                ('category', models.CharField(choices=[('writing', 'Writing'), ('coding', 'Coding'), ('research', 'Research'), ('design', 'Design'), ('data', 'Data Entry'), ('analysis', 'Analysis'), ('other', 'Other')], default='other', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('completed', 'Completed')], default='open', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('max_submissions', models.IntegerField(default=20)),
                ('evaluation_criteria', models.TextField(blank=True, help_text='Specific criteria for AI evaluation')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_tasks', to=settings.AUTH_USER_MODEL)),
                ('min_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='core.level')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('ai_score', models.FloatField(blank=True, null=True)),
                ('ai_feedback', models.TextField(blank=True)),
                ('ai_strengths', models.TextField(blank=True)),
                ('ai_improvements', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('evaluating', 'Evaluating'), ('evaluated', 'Evaluated'), ('rejected', 'Rejected')], default='pending', max_length=12)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('evaluated_at', models.DateTimeField(blank=True, null=True)),
                ('earnings', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='core.task')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
                'unique_together': {('task', 'worker')},
            },
        ),
    ]
